yarnPath: .yarn/releases/yarn-3.3.1.cjs
nodeLinker: node-modules

packageExtensions:
  "@nrwl/devkit@*":
    peerDependencies:
      typescript: "^3 || ^4"
  "@nrwl/eslint-plugin-nx@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
      eslint: "^6.0.0 || ^7.0.0 || ^8.0.0"
  "@nrwl/jest@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/js@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/linter@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/react@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/workspace@*":
    peerDependencies:
      typescript: "^3 || ^4"
